package annotation_viewer;

/**
 *
 * @author Alex
 * @version 2.0
 * @since 8-4-2016
 */
public class CurrentDatabase extends javax.swing.JFrame {
    
    //// Fields
    
    private ChooseDatabaseDetails database;
    
    //// Constructor
    
    /**
     * 
     * Creates new form CurrentDatabase
     */ 
    public CurrentDatabase() {
        initComponents();
        
        database = new ChooseDatabaseDetails();
        current_URL.setText(database.getDatabase_url());
        current_Username.setText(database.getUsername());
        current_Password.setText(database.getPassword());
        current_primarySequenceQuery.setText(database.getSequenceQuery());
        current_AnnotationQuery.setText(database.getAnnotationQuery());
        
        setVisible(true);
        pack();
    }
    
    //// Methods
    
    /**
     * Updates the user modified database credentials.
     * Prints the database credentials as a backgroundcheck.
     */
    private void setDatabaseDetails(){
        database.setDatabase_url(current_URL.getText());
        database.setUsername(current_Username.getText());
        database.setPassword(current_Password.getText());
        database.setSequenceQuery(current_primarySequenceQuery.getText());
        database.setAnnotationQuery(current_AnnotationQuery.getText());
        
        // Prints the current database credentials as a check to confirm the change.
        System.out.println("current url: "+database.getDatabase_url());
        System.out.println("current username: "+database.getUsername());
        System.out.println("current password: "+database.getPassword());
        System.out.println("current sequence query: "+database.getSequenceQuery());
        System.out.println("current annotation query: "+database.getAnnotationQuery());
        System.out.println("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentDatabaseDetails_label = new javax.swing.JLabel();
        databaseURL_label = new javax.swing.JLabel();
        databaseUsername_label = new javax.swing.JLabel();
        databasePassword_label = new javax.swing.JLabel();
        current_URL = new javax.swing.JTextField();
        current_Username = new javax.swing.JTextField();
        current_Password = new javax.swing.JTextField();
        updateDetails_button = new javax.swing.JButton();
        updateDatabase_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        current_primarySequenceQuery = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        current_AnnotationQuery = new javax.swing.JTextField();

        setTitle("Database Details");

        currentDatabaseDetails_label.setText("Current Database Details:");

        databaseURL_label.setText("Database URL: ");

        databaseUsername_label.setText("Database Username: ");

        databasePassword_label.setText("Database Password: ");

        current_URL.setText("url");

        current_Username.setText("username");

        current_Password.setText("password");

        updateDetails_button.setText("Update");
        updateDetails_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetails_buttonActionPerformed(evt);
            }
        });

        updateDatabase_label.setText("Click here to update Database details");

        jLabel1.setText("Current Queries:");

        jLabel2.setText("Primary Sequence: ");

        current_primarySequenceQuery.setText("query");

        jLabel3.setText("Annotation: ");

        current_AnnotationQuery.setText("query");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updateDatabase_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateDetails_button, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(current_primarySequenceQuery))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(48, 48, 48)
                                .addComponent(current_AnnotationQuery))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(databaseUsername_label)
                                    .addComponent(databaseURL_label)
                                    .addComponent(databasePassword_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(current_URL)
                                    .addComponent(current_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(current_Password)))
                            .addComponent(currentDatabaseDetails_label)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentDatabaseDetails_label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(databaseURL_label)
                    .addComponent(current_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(databaseUsername_label)
                    .addComponent(current_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(current_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(databasePassword_label))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(current_primarySequenceQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(current_AnnotationQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateDetails_button)
                    .addComponent(updateDatabase_label))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gets clicked when the database credentials in the GUI are updated.
     * @param evt 
     */
    private void updateDetails_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetails_buttonActionPerformed
        setDatabaseDetails();
    }//GEN-LAST:event_updateDetails_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentDatabaseDetails_label;
    private javax.swing.JTextField current_AnnotationQuery;
    private javax.swing.JTextField current_Password;
    private javax.swing.JTextField current_URL;
    private javax.swing.JTextField current_Username;
    private javax.swing.JTextField current_primarySequenceQuery;
    private javax.swing.JLabel databasePassword_label;
    private javax.swing.JLabel databaseURL_label;
    private javax.swing.JLabel databaseUsername_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel updateDatabase_label;
    private javax.swing.JButton updateDetails_button;
    // End of variables declaration//GEN-END:variables

    
}
